use_frameworks!

target 'DLKit_Example' do
  pod 'DLKit', :path => '../'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'SVPullToRefresh', '~> 0.4.1'

  target 'DLKit_Tests' do
    inherit! :search_paths
    pod 'SVPullToRefresh', '~> 0.4.1'
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
